# BaseDeDatos/MetaDatos/paises.py

# Diccionario maestro: Nombre del país -> Código ISO 3 letras
PAISES_MPS = {
    "Liechtenstein": "LIE", "Vaticano": "VAT", "Singapur": "SGP", "Mónaco": "MCO", 
    "Suiza": "CHE", "Andorra": "AND", "Noruega": "NOR", "Hong Kong": "HKG", 
    "Irlanda": "IRL", "Catar": "QAT", "Países Bajos": "NLD", "Luxemburgo": "LUX", 
    "San Marino": "SMR", "Taiwán": "TWN", "Estonia": "EST", "Islandia": "ISL", 
    "Australia": "AUS", "Bahamas": "BHS", "Finlandia": "FIN", "Dinamarca": "DNK", 
    "Nueva Zelanda": "NZL", "Canadá": "CAN", "Lituania": "LTU", "Corea del Sur": "KOR", 
    "Reino Unido": "GBR", "Japón": "JPN", "Suecia": "SWE", "Kuwait": "KWT", 
    "Seychelles": "SYC", "Rep. Checa": "CZE", "Emiratos Árabes": "ARE", "Bélgica": "BEL", 
    "Austria": "AUT", "Estados Unidos": "USA", "Eslovenia": "SVN", "Alemania": "DEU", 
    "Uruguay": "URY", "Brunéi": "BRN", "Letonia": "LVA", "Barbados": "BRB", 
    "Santa Lucía": "LCA", "Chipre": "CYP", "Chile": "CHL", "Malta": "MLT", 
    "Eslovaquia": "SVK", "San Cristóbal y Nieves": "KNA", "Mauricio": "MUS", 
    "Georgia": "GEO", "Botsuana": "BWA", "Nauru": "NRU", "Francia": "FRA", 
    "Polonia": "POL", "Dominica": "DMA", "España": "ESP", "Costa Rica": "CRI", 
    "Portugal": "PRT", "Granada": "GRD", "Bután": "BTN", "Omán": "OMN", 
    "Israel": "ISR", "Tuvalu": "TUV", "San Vicente": "VCT", "Rumania": "ROU", 
    "Palaos": "PLW", "Baréin": "BHR", "Maldivas": "MDV", "Tonga": "TON", 
    "Ruanda": "RWA", "Italia": "ITA", "Montenegro": "MNE", "Croacia": "HRV", 
    "Hungría": "HUN", "Malasia": "MYS", "Namibia": "NAM", "Cabo Verde": "CPV", 
    "Túnez": "TUN", "Vanuatu": "VUT", "Arabia Saudí": "SAU", "Jamaica": "JAM", 
    "Kiribati": "KIR", "Antigua y Barbuda": "ATG", "Samoa": "WSM", 
    "Islas Marshall": "MHL", "Indonesia": "IDN", "Bulgaria": "BGR", 
    "Trinidad y Tobago": "TTO", "Armenia": "ARM", "Fiyi": "FJI", "Moldavia": "MDA", 
    "Jordania": "JOR", "Ghana": "GHA", "Tailandia": "THA", "Grecia": "GRC", 
    "Serbia": "SRB", "Macedonia del Norte": "MKD", "Albania": "ALB", 
    "Colombia": "COL", "India": "IND", "Micronesia": "FSM", "Sudáfrica": "ZAF", 
    "Paraguay": "PRY", "Rep. Dominicana": "DOM", "Timor Oriental": "TLS", 
    "Tanzania": "TZA", "Belice": "BLZ", "Senegal": "SEN", "Kazajistán": "KAZ", 
    "Costa de Marfil": "CIV", "Panamá": "PAN", "Brasil": "BRA", "Marruecos": "MAR", 
    "Surinam": "SUR", "Perú": "PER", "Filipinas": "PHL", "Benín": "BEN", 
    "Kosovo": "XKX", "Azerbaiyán": "AZE", "Kenia": "KEN", "Argentina": "ARG", 
    "Bosnia": "BIH", "Bangladés": "BGD", "Gambia": "GMB", "Nepal": "NPL", 
    "Ecuador": "ECU", "Guyana": "GUY", "México": "MEX", "Zambia": "ZMB", 
    "Uganda": "UGA", "Lesoto": "LSO", "Mongolia": "MNG", "Guatemala": "GTM", 
    "Uzbekistán": "UZB", "Vietnam": "VNM", "China": "CHN", "El Salvador": "SLV", 
    "Argelia": "DZA", "Mauritania": "MRT", "Bolivia": "BOL", "Camerún": "CMR", 
    "Islas Salomón": "SLB", "Nigeria": "NGA", "Pakistán": "PAK", 
    "Burkina Faso": "BFA", "Suazilandia": "SWZ", "Togo": "TGO", 
    "Santo Tomé y Príncipe": "STP", "Bielorrusia": "BLR", "Egipto": "EGY", 
    "Gabón": "GAB", "Turquía": "TUR", "Malaui": "MWI", "Sierra Leona": "SLE", 
    "Kirguistán": "KGZ", "Rusia": "RUS", "Níger": "NER", "Mali": "MLI", 
    "Guinea": "GIN", "Madagascar": "MDG", "Mozambique": "MOZ", 
    "Papúa Nueva Guinea": "PNG", "Comoras": "COM", "Yibuti": "DJI", 
    "Camboya": "KHM", "Honduras": "HND", "Tayikistán": "TJK", "Laos": "LAO", 
    "Ucrania": "UKR", "Chad": "TCD", "Zimbabue": "ZWE", "Liberia": "LBR", 
    "Nicaragua": "NIC", "Irán": "IRN", "Etiopía": "ETH", "Guinea-Bisáu": "GNB", 
    "Angola": "AGO", "Burundi": "BDI", "Congo": "COG", "Palestina": "PSE", 
    "Sudán": "SDN", "R.D. Congo": "COD", "Cuba": "CUB", "Guinea Ecuatorial": "GNQ", 
    "Libia": "LBY", "Rep. Centroafricana": "CAF", "Afganistán": "AFG", 
    "Somalia": "SOM", "Irak": "IRQ", "Sudán del Sur": "SSD", "Myanmar": "MMR", 
    "Turkmenistán": "TKM", "Haití": "HTI", "Corea del Norte": "PRK", 
    "Eritrea": "ERI", "Venezuela": "VEN", "Líbano": "LBN", "Siria": "SYR", "Yemen": "YEM"
}

def obtener_paises():
    return PAISES_MPS